"""empty message

Revision ID: 0002
Revises: 0001
Create Date: 2022-04-14 23:50:49.336247

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("is_secret", sa.Boolean(), nullable=True))
    op.add_column("sections", sa.Column("is_secret", sa.Boolean(), nullable=True))
    op.drop_column("pages", "is_admin_only")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("is_admin_only", sa.BOOLEAN(), nullable=True))
    op.drop_column("sections", "is_secret")
    op.drop_column("pages", "is_secret")
    # ### end Alembic commands ###
