"""Add a parent_page_id for link tree

Revision ID: 0004
Revises: 0003
Create Date: 2022-04-25 19:03:01.778046

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pages",
        sa.Column("parent_page_id", fastapi_users_db_sqlalchemy.guid.GUID()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pages", "parent_page_id")
    # ### end Alembic commands ###
