#!/bin/bash
command_verb=$1
shift
if [ "$command_verb" == "generate" ]; then
  rev_id=$1
  message=$2
  shift;shift
  if [ -z "$rev_id" ] || [ -z "$message" ]; then
    echo "usage: script/migrations generate <revision number> '<message>'"
    exit 1
  fi
  pipenv run alembic revision --autogenerate
elif [ "$command_verb" == "run" ]; then
  pipenv run alembic upgrade head
else
  echo "Expected one of generate|run"
  exit 1
fi
